window.AIOS_TRANSLATIONS = {
  vi:{
    nav:{products:'Công cụ AI',results:'Cách hoạt động',pricing:'Bảng giá',help:'Trợ giúp',signin:'Đăng nhập',signup:'Bắt đầu miễn phí'},
    common:{tryFree:'Dùng thử miễn phí',create:'Tạo ngay',choose:'Chọn gói này'},
    hero:{eyebrow:'AI THỰC CHIẾN • DỄ HIỂU • DỄ DÙNG',titleLead:'AI đơn giản',titleAccent:'cho công việc mỗi ngày.',subtitle:'Biến ý tưởng thành nội dung, hình ảnh và kết quả thực tế bằng những công cụ AI dễ dùng.',primary:'Khám phá công cụ',secondary:'Xem cách hoạt động'},
    showcase:{prompt:'Hôm nay bạn muốn tạo điều gì?',write:'Viết nội dung',image:'Tạo hình ảnh',analyze:'Phân tích',idea:'Ý tưởng',simple:'Đơn giản',ready:'Sẵn sàng dùng'},
    outcomes:{smartTitle:'Làm việc thông minh hơn',smartText:'Giảm việc lặp lại và tiết kiệm thời gian.',peopleTitle:'AI dành cho mọi người',peopleText:'Không cần biết lập trình hay kỹ thuật phức tạp.',realTitle:'Kết quả thực tế',realText:'Ứng dụng ngay vào công việc và kinh doanh.'},
    paths:{title:'CHỌN NHANH',seller:'Tôi bán hàng',content:'Tôi làm nội dung',photo:'Tôi muốn ảnh đẹp',all:'Tất cả công cụ',sellerText:'Ảnh và nội dung bán hàng.',contentText:'Nội dung sẵn sàng đăng.',photoText:'Chân dung và phong cách.',allText:'Toàn bộ công cụ đang hoạt động.'},
    skills:{title:'CÔNG CỤ CHO VIỆC THẬT',intro:'Chọn đúng công cụ, mô tả điều bạn cần và bắt đầu ngay.',viewAll:'Xem tất cả công cụ',all:'Tất cả',seller:'Bán hàng',content:'Nội dung',photo:'Hình ảnh',work:'Công việc',open:'Dùng công cụ'},
    results:{title:'TỪ Ý TƯỞNG ĐẾN KẾT QUẢ',intro:'Những việc quen thuộc, nay được làm nhanh và rõ ràng hơn.',facebook:'Viết bài Facebook',product:'Tạo ảnh sản phẩm',portrait:'Tạo/chỉnh chân dung',tryon:'Thử trang phục',description:'Viết mô tả sản phẩm',plan:'Lên kế hoạch nội dung',shorten:'Biến bài dài thành bài ngắn',ads:'Lên ý tưởng quảng cáo'},
    how:{title:'BẮT ĐẦU THẬT DỄ',steps:[['01','Chọn công cụ','Chọn công cụ phù hợp với việc bạn cần.'],['02','Mô tả điều bạn cần','Nhập nội dung hoặc tải hình ảnh của bạn.'],['03','Nhận kết quả','Xem kết quả và tiếp tục sử dụng ngay.']]},
    pricing:{title:'BẢNG GIÁ',month:'/tháng',recommended:'ĐỀ XUẤT',includes:'Bao gồm'},
    faq:{title:'CÂU HỎI THƯỜNG GẶP',items:[['Tôi có cần biết viết prompt?','Không. Chỉ cần mô tả điều bạn cần bằng ngôn ngữ tự nhiên và chọn công cụ phù hợp.'],['Tôi có thể dùng thử trước khi trả phí?','Có. Bạn có thể bắt đầu với gói Free và tự đánh giá kết quả trước khi chọn gói khác.'],['Công cụ hình ảnh hoạt động thế nào?','Tải ảnh tham chiếu, chọn phong cách hoặc điểm đến, thêm yêu cầu rồi nhấn Tạo ngay.']]},
    finalCta:{title:'Biến ý tưởng thành kết quả ngay hôm nay.',text:'Chọn một công cụ và bắt đầu bằng điều bạn đang cần.'},
    launcher:{workspace:'Kết quả của bạn',resultTitle:'Kết quả sẽ xuất hiện tại đây',resultText:'Nhập yêu cầu để bắt đầu.',working:'Đang tạo ảnh, vui lòng chờ…',textWorking:'Đang tạo nội dung, vui lòng chờ…',ready:'Đã tiếp nhận yêu cầu',readyText:'Bạn có thể tiếp tục với một yêu cầu khác.',imageRequired:'Vui lòng tải lên một ảnh sản phẩm.',portraitRequired:'Vui lòng tải lên một ảnh chân dung.',referenceRequired:'Vui lòng tải lên một ảnh tham chiếu.',generationError:'Không thể tạo ảnh lúc này. Vui lòng thử lại.',tryAgain:'Kiểm tra ảnh và yêu cầu của bạn rồi thử lại.',textGenerationError:'Không thể tạo nội dung lúc này.',textTryAgain:'Kiểm tra nội dung đầu vào rồi thử lại.',generatedAlt:'Ảnh sản phẩm đã tạo',worldGeneratedAlt:'Ảnh check-in thế giới đã tạo',upload:'Tải ảnh tham chiếu',uploadHint:'PNG, JPG hoặc WEBP',preset:'Phong cách gợi ý (không bắt buộc)',destination:'Điểm đến',destinationPlaceholder:'Ví dụ: Paris, Kyoto, Santorini…',mainInput:'Nội dung đầu vào',mainPlaceholder:'Nhập nội dung hoặc thông tin bạn muốn xử lý…',context:'Mục tiêu, giọng điệu hoặc bối cảnh (không bắt buộc)',contextPlaceholder:'Ví dụ: chuyên nghiệp, ngắn gọn, dành cho người mới…',extra:'Yêu cầu thêm theo ý bạn',extraPlaceholder:'Ví dụ: đổi trang phục, tóc xoăn nhẹ, nền Paris, ánh sáng hoàng hôn…',variations:'Số lượng biến thể',scene:'Bối cảnh / phong cách',angle:'Góc máy',use:'Mục đích sử dụng',usePlaceholder:'Ví dụ: ảnh bìa gian hàng, quảng cáo mạng xã hội…'},
    footer:{blurb:'AI thực chiến • dễ hiểu • dễ dùng',product:'Khám phá',tools:'Công cụ AI',support:'Hỗ trợ',contact:'Liên hệ',account:'Tài khoản',signin:'Đăng nhập',signup:'Đăng ký',legal:'Pháp lý',terms:'Điều khoản',privacy:'Quyền riêng tư',note:'AI đơn giản cho công việc mỗi ngày.'}
  },
  en:{
    nav:{products:'AI tools',results:'How it works',pricing:'Pricing',help:'Help',signin:'Sign in',signup:'Start free'},common:{tryFree:'Try for free',create:'Create now',choose:'Choose plan'},
    hero:{eyebrow:'PRACTICAL AI • CLEAR • EASY TO USE',titleLead:'Simple AI',titleAccent:'for everyday work.',subtitle:'Turn ideas into content, images, and practical results with easy-to-use AI tools.',primary:'Explore tools',secondary:'See how it works'},
    showcase:{prompt:'What would you like to create today?',write:'Write content',image:'Create images',analyze:'Analyze',idea:'Ideas',simple:'Simple',ready:'Ready to use'},
    outcomes:{smartTitle:'Work smarter',smartText:'Reduce repetitive work and save time.',peopleTitle:'AI for everyone',peopleText:'No coding or complex technical knowledge needed.',realTitle:'Practical results',realText:'Apply results directly to work and business.'},
    paths:{title:'QUICK START',seller:'Selling',content:'Content',photo:'Images',all:'All tools',sellerText:'Sales images and content.',contentText:'Publish-ready content.',photoText:'Portrait and style.',allText:'Every working tool.'},
    skills:{title:'TOOLS FOR REAL WORK',intro:'Choose a tool, describe what you need, and get started.',viewAll:'View all tools',all:'All',seller:'Selling',content:'Content',photo:'Images',work:'Work',open:'Use tool'},
    results:{title:'FROM IDEA TO RESULT',intro:'Everyday tasks, made faster and clearer.',facebook:'Write Facebook posts',product:'Create product images',portrait:'Create/edit portraits',tryon:'Try on clothing',description:'Write product descriptions',plan:'Plan content',shorten:'Turn long posts into short ones',ads:'Develop ad ideas'},
    how:{title:'EASY TO START',steps:[['01','Choose a tool','Pick the right tool for your task.'],['02','Describe what you need','Enter content or upload your image.'],['03','Get your result','Review the result and put it to use.']]},
    pricing:{title:'PRICING',month:'/month',recommended:'RECOMMENDED',includes:'Includes'},
    faq:{title:'FREQUENTLY ASKED QUESTIONS',items:[['Do I need to know how to write prompts?','No. Describe what you need naturally and choose the right tool.'],['Can I try before paying?','Yes. Start with the Free plan and evaluate the results before choosing another plan.'],['How do image tools work?','Upload a reference, select a style or destination, add instructions, and press Create now.']]},
    finalCta:{title:'Turn your idea into a result today.',text:'Choose a tool and begin with what you need now.'},
    launcher:{workspace:'Your result',resultTitle:'Your result will appear here',resultText:'Enter a request to begin.',working:'Creating your image…',textWorking:'Creating your content…',ready:'Request received',readyText:'You can continue with another request.',imageRequired:'Please upload a product image.',portraitRequired:'Please upload a portrait.',referenceRequired:'Please upload a reference image.',generationError:'Unable to create an image right now.',tryAgain:'Check your image and request, then try again.',textGenerationError:'Unable to create content right now.',textTryAgain:'Check your input and try again.',generatedAlt:'Generated product image',worldGeneratedAlt:'Generated world check-in image',upload:'Upload a reference image',uploadHint:'PNG, JPG, or WEBP',preset:'Suggested style (optional)',destination:'Destination',destinationPlaceholder:'For example: Paris, Kyoto, Santorini…',mainInput:'Main input',mainPlaceholder:'Enter the content or information to process…',context:'Goal, tone, or context (optional)',contextPlaceholder:'For example: professional, concise, for beginners…',extra:'Additional request',extraPlaceholder:'For example: change clothing, soft curls, Paris setting, sunset light…',variations:'Variations',scene:'Scene / style',angle:'Camera angle',use:'Intended use',usePlaceholder:'For example: storefront cover, social ad…'},
    footer:{blurb:'Practical AI • clear • easy to use',product:'Explore',tools:'AI tools',support:'Support',contact:'Contact',account:'Account',signin:'Sign in',signup:'Sign up',legal:'Legal',terms:'Terms',privacy:'Privacy',note:'Simple AI for everyday work.'}
  }
};
