window.AIOS_TRANSLATIONS = {
  vi:{
    nav:{products:'Sản phẩm',results:'Kết quả',pricing:'Gói dịch vụ',help:'Trợ giúp',signin:'Đăng nhập',signup:'Bắt đầu miễn phí'},
    common:{tryFree:'Dùng thử miễn phí',create:'Tạo ngay',choose:'Chọn gói này'},
    hero:{eyebrow:'AI THỰC DỤNG · KẾT QUẢ THẬT',titleLead:'AI kiến tạo',titleAccent:'tương lai.',subtitle:'Đơn giản hóa thế giới phức tạp cùng AI.',primary:'Khám phá công cụ',secondary:'Thử tạo ảnh'},
    showcase:{result:'Khung kết quả',commerce:'Hình ảnh thương mại',identity:'Giữ đúng nhận diện'},
    paths:{title:'CHỌN NHANH',seller:'Tôi bán hàng',content:'Tôi làm content',photo:'Tôi muốn ảnh đẹp',all:'Tôi muốn tất cả',sellerText:'Ảnh và nội dung bán hàng.',contentText:'Nội dung sẵn sàng đăng.',photoText:'Chân dung và phong cách.',allText:'Toàn bộ công cụ AIOS Lab.'},
    skills:{title:'AI CHUYÊN SÂU',viewAll:'Xem tất cả công cụ',all:'Tất cả',seller:'Bán hàng',content:'Nội dung',photo:'Hình ảnh',work:'Công việc',open:'Mở công cụ'},
    results:{title:'KẾT QUẢ',replaceable:'Vị trí đầu ra có thể thay thế',contentTitle:'Bản nháp nội dung'},
    how:{title:'QUY TRÌNH',steps:[['01','Chọn công cụ','Chọn đúng năng lực cho việc cần làm.'],['02','Gửi yêu cầu','Tải ảnh hoặc nhập nội dung.'],['03','Nhận kết quả','Xem, tinh chỉnh và sử dụng kết quả.']]},
    pricing:{title:'GÓI DỊCH VỤ',month:'/tháng',recommended:'ĐỀ XUẤT',includes:'Bao gồm'},
    faq:{title:'CÂU HỎI',items:[['Tôi có cần biết viết prompt?','Không. Hãy mô tả điều bạn cần bằng ngôn ngữ tự nhiên và chọn công cụ phù hợp.'],['Tôi có thể dùng thử trước khi trả phí?','Có. Bạn có thể bắt đầu với gói Free và tự đánh giá kết quả trước khi chọn gói khác.'],['Công cụ ảnh hoạt động thế nào?','Tải ảnh tham chiếu, chọn phong cách hoặc điểm đến, thêm yêu cầu rồi gửi để công cụ xử lý. Product Photo và World Check-in hiện hỗ trợ tạo ảnh trực tiếp.']]},
    launcher:{resultTitle:'Kết quả sẽ xuất hiện tại đây',resultText:'Nhập yêu cầu để bắt đầu.',working:'Đang tạo ảnh, vui lòng chờ…',ready:'Đã tiếp nhận yêu cầu',readyText:'Bạn có thể tiếp tục với một yêu cầu khác.',imageRequired:'Vui lòng tải lên một ảnh sản phẩm.',referenceRequired:'Vui lòng tải lên một ảnh tham chiếu.',generationError:'Không thể tạo ảnh lúc này. Vui lòng thử lại.',tryAgain:'Kiểm tra ảnh và yêu cầu của bạn rồi thử lại.',generatedAlt:'Ảnh sản phẩm đã tạo',worldGeneratedAlt:'Ảnh check-in thế giới đã tạo',upload:'Tải ảnh tham chiếu',uploadHint:'PNG, JPG hoặc WEBP',preset:'Phong cách gợi ý (không bắt buộc)',destination:'Điểm đến',destinationPlaceholder:'Ví dụ: Paris, Kyoto, Santorini…',mainInput:'Nội dung đầu vào',mainPlaceholder:'Nhập nội dung hoặc thông tin bạn muốn xử lý…',context:'Mục tiêu, giọng điệu hoặc bối cảnh (không bắt buộc)',contextPlaceholder:'Ví dụ: chuyên nghiệp, ngắn gọn, dành cho người mới…',extra:'Yêu cầu thêm theo ý bạn',extraPlaceholder:'Ví dụ: đổi trang phục, tóc xoăn nhẹ, nền Paris, ánh sáng hoàng hôn…',variations:'Số lượng biến thể',scene:'Bối cảnh / phong cách',angle:'Góc máy',use:'Mục đích sử dụng',usePlaceholder:'Ví dụ: ảnh bìa gian hàng, quảng cáo mạng xã hội…'},
    footer:{blurb:'AI chuyên sâu cho những công việc thực tế.',product:'Sản phẩm',tools:'Công cụ AI',support:'Hỗ trợ',contact:'Liên hệ',account:'Tài khoản',signin:'Đăng nhập',signup:'Đăng ký',legal:'Pháp lý',terms:'Điều khoản',privacy:'Quyền riêng tư',note:'AI thực dụng. Kết quả rõ ràng.'}
  },
  en:{
    nav:{products:'Products',results:'Results',pricing:'Plans',help:'Help',signin:'Sign in',signup:'Start free'},common:{tryFree:'Try for free',create:'Create now',choose:'Choose plan'},
    hero:{eyebrow:'PRACTICAL AI · REAL RESULTS',titleLead:'AI creates',titleAccent:'the future.',subtitle:'Simplify a complex world with AI.',primary:'Explore tools',secondary:'Try image creation'},
    showcase:{result:'Result frame',commerce:'Commercial imagery',identity:'Identity preserved'},
    paths:{title:'QUICK START',seller:'I sell online',content:'I create content',photo:'I want better photos',all:'I want everything',sellerText:'Sales images and content.',contentText:'Publish-ready content.',photoText:'Portrait and style.',allText:'Every AIOS Lab tool.'},
    skills:{title:'SPECIALIST AI',viewAll:'View all tools',all:'All',seller:'Selling',content:'Content',photo:'Images',work:'Work',open:'Open tool'},
    results:{title:'RESULTS',replaceable:'Replaceable output slot',contentTitle:'Content draft'},
    how:{title:'PROCESS',steps:[['01','Choose a tool','Match the right capability to your task.'],['02','Send your request','Upload an image or enter content.'],['03','Get your result','Review, refine, and use the result.']]},
    pricing:{title:'PLANS',month:'/month',recommended:'RECOMMENDED',includes:'Includes'},
    faq:{title:'QUESTIONS',items:[['Do I need to know how to write prompts?','No. Describe what you need naturally and choose the relevant tool.'],['Can I try before paying?','Yes. Start with Free and assess the experience before choosing another plan.'],['How do image tools work?','Upload a reference, choose a style or destination, add instructions, and submit. Product Photo and World Check-in currently support direct image generation.']]},
    launcher:{resultTitle:'Your result will appear here',resultText:'Enter a request to begin.',working:'Generating images, please wait…',ready:'Request received',readyText:'You can continue with another request.',imageRequired:'Please upload a product image.',referenceRequired:'Please upload a reference image.',generationError:'Images could not be generated right now.',tryAgain:'Check your image and request, then try again.',generatedAlt:'Generated product image',worldGeneratedAlt:'Generated world check-in image',upload:'Upload reference image',uploadHint:'PNG, JPG, or WEBP',preset:'Suggested style (optional)',destination:'Destination',destinationPlaceholder:'For example: Paris, Kyoto, Santorini…',mainInput:'Input content',mainPlaceholder:'Enter the content or information to process…',context:'Goal, tone, or context (optional)',contextPlaceholder:'For example: professional, concise, for beginners…',extra:'Add your own instructions',extraPlaceholder:'For example: change outfit, soft curls, Paris background, sunset light…',variations:'Number of variations',scene:'Scene / style',angle:'Camera angle',use:'Intended use',usePlaceholder:'For example: storefront cover, social ad…'},
    footer:{blurb:'Specialist AI for practical work.',product:'Product',tools:'AI tools',support:'Support',contact:'Contact',account:'Account',signin:'Sign in',signup:'Sign up',legal:'Legal',terms:'Terms',privacy:'Privacy',note:'Practical AI. Clear results.'}
  }
};
